version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
